### ISSUE TITLE
Error on parsing even the example

### ISSUE THREAD

**Issue by codeyogi911** [Sleavely/Bark-JS#13]
Hello,
I was trying your library to parse GS1 codes in a react-native project. But even running the example gives me the following error.
![IMG_2007](https://user-images.githubusercontent.com/29333988/109110268-bfee3000-7771-11eb-84ba-b92a36da2101.PNG)

**Comment by Sleavely** [comment]
That's odd. Could you provide which bark-js version you are using and the original barcode string (or a photo) you are attempting to parse?

**Comment by Sleavely** [comment]
On second thought I think it may be bundling thing since bark-js never declares a `_this` variable. What does your build process look like?

**Comment by Sleavely** [comment]
I'm closing this since there is not much I can do to troubleshoot further without additional information. Leave a comment or open a new issue if there's anything I can do to help 👋
