### ISSUE TITLE
Unable to parse a barcode that contains a date

### ISSUE THREAD

**Issue by reidprojects** [Sleavely/Bark-JS#23]
Since I updated to the latest version, the decoding fails as soon as their is a date AI in the barcode. 

Tested with AI 11 and 17, same behavior.

After investigation, this is linked to the changes made in d01ae5a

It looks like `this` is undefined, so I would suggest to go back with exports.

**Comment by Sleavely** [comment]
Would you mind elaborating a little bit on how you build your project, do you for example use something like Webpack or Rollup that modifies the code of your dependencies?

A similar issue was [posted a while back](https://github.com/Sleavely/Bark-JS/issues/13#issuecomment-785660055) but I would really like to understand the issue before making modifications
